### ISSUE TITLE
Api key and PII exposed in logs

### ISSUE THREAD

**Issue by SSmietana** [gettilled/tilled-node#67]
Similar to https://github.com/gettilled/tilled-node/issues/18 I'm still seeing `tilled-api-key` exposed in error logs. It appears that https://github.com/gettilled/tilled-node/pull/20 only resolved this for successful requests.

I'm also curious if you could implement or add a some sort of config option to facilitate redacting PII data from logs (card number, cvc, address info, etc). This appears to always be included under `response.config.data` or `error.config.data`.

```json
{
  "error": {
    "code": "ERR_BAD_REQUEST",
    "config": {
      "adapter": ["xhr", "http", "fetch"],
      "data": "{\"card\":{\"number\":\"4111111111111111\",\"exp_month\":5,\"exp_year\":2020,\"cvc\":\"123\"},\"billing_details\":{\"address\":{\"street\":\"123 Main St.\",\"city\":\"Salem\",\"state\":\"OR\",\"zip\":\"97302\",\"country\":\"us\"}},\"metadata\":{\"homeId\":\"eEiOihrIPnIQ3dSdiH3_J\",\"taxableEntityId\":\"4bOQr_W18a-DWsZtO9iUj\"},\"type\":\"card\"}",
      "env": {},
      "headers": {
        "Accept": "application/json, text/plain, */*",
        "Accept-Encoding": "gzip, compress, deflate, br",
        "Content-Length": "295",
        "Content-Type": "application/json",
        "User-Agent": "axios/1.7.4",
        "tilled-account": "acct_FuzzIyLt3lvkQW8OgbixP",
        "tilled-api-key": "sk_<REAL_VALUE>",
        "tilled-client-name": "tilled-node",
        "tilled-client-version": "1.0.5"
      },
      "maxBodyLength": -1,
      "maxContentLength": -1,
      "method": "post",
      "timeout": 0,
      "transformRequest": [null],
      "transformResponse": [null],
      "transitional": {
        "clarifyTimeoutError": false,
        "forcedJSONParsing": true,
        "silentJSONParsing": true
      },
      "url": "https://sandbox-api.tilled.com/v1/payment-methods",
      "xsrfCookieName": "XSRF-TOKEN",
      "xsrfHeaderName": "X-XSRF-TOKEN"
    },
    "message": "Request failed with status code 400",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 400\n    at settle (/fairly/node_modules/.pnpm/axios@1.7.4/node_modules/axios/dist/node/axios.cjs:2015:12)\n    at IncomingMessage.handleStreamEnd (/fairly/node_modules/.pnpm/axios@1.7.4/node_modules/axios/dist/node/axios.cjs:3131:11)\n    at IncomingMessage.emit (node:events:530:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (/fairly/node_modules/.pnpm/axios@1.7.4/node_modules/axios/dist/node/axios.cjs:4262:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async TilledApiClient.createPaymentMethod (/fairly/money/money-api/dist/index.js:16449:12)\n    at async TilledPaymentGateway.createGuestPaymentMethod (/fairly/money/money-api/dist/index.js:14864:18)\n    at async GuestPaymentLogic.createPaymentMethod (/fairly/money/money-api/dist/index.js:14670:32)\n    at async Object.createGuestPaymentMethod (/fairly/money/money-api/dist/index.js:14778:14)\n    at async middleware (/fairly/node_modules/.pnpm/graphql-shield@7.6.5_graphql-middleware@6.1.35_graphql@16.9.0__graphql@16.9.0/node_modules/graphql-shield/cjs/generator.js:30:24)\n    at async resolve (/fairly/packages/server/dist/index.js:223:30)",
    "status": 400
  }
}
```

**Comment by dpatton1992** [comment]
Thanks for bringing this to our attention @SSmietana. We are reviewing the issue.

**Comment by dpatton1992** [comment]
@SSmietana I made some changes to the BaseAPI which should address the issues outlined here:
![image](https://github.com/user-attachments/assets/8b4f7f6a-a61f-41b8-9f40-2a6932554337)
Once these changes are approved and merged, we should start redacting secret keys, numbers, cvc, account_number, institution_id, transit_number, routing_number, street, email, and phone. 

If you have any feedback, please reach out.

**Comment by SSmietana** [comment]
Awesome, thank you @dpatton1992
